# Generated by Django 5.2.5 on 2026-04-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_variation_variation_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='userporfile',
            new_name='userprofile',
        ),
        migrations.DeleteModel(
            name='ReviewRatingTranslation',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='review',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
