# Generated by Django 5.2.5 on 2026-01-20 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'product gallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
