# Generated by Django 5.2.5 on 2026-01-22 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_profile_picture'),
        ('product', '0006_alter_productgallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='userporfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
