# Generated by Django 5.2.5 on 2026-01-22 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_profile_picture'),
        ('product', '0007_reviewrating_userporfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='userporfile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
